import { Patient, PatientStat } from "./types";

export const patientStats: PatientStat[] = [
  {
    id: "total",
    label: "Total patients",
    value: "321",
    changeLabel: "12% vs last month",
    changeDirection: "up",
  },
  {
    id: "new",
    label: "New patients",
    value: "28",
    changeLabel: "18% vs last month",
    changeDirection: "up",
  },
  {
    id: "active",
    label: "Active patients",
    value: "263",
    changeLabel: "9% vs last month",
    changeDirection: "up",
  },
  {
    id: "followups",
    label: "Follow-ups",
    value: "54",
    changeLabel: "6% vs last month",
    changeDirection: "down",
  },
];

export const patients: Patient[] = [
  {
    id: "anna-johansen",
    name: "Anna Johansen",
    initials: "AJ",
    avatarClassName: "bg-violet-100 text-violet-700",
    age: 34,
    gender: "Female",
    email: "anna.johansen@example.com",
    phone: "+47 912 34 567",
    status: "Active",
    lastVisit: "12 May 2026",
    dateOfBirth: "12 Feb 1992",
    address: "Storgata 10, 0155 Oslo, Norway",
    allergies: "Penicillin, Pollen",
    conditions: "Migraine, Allergic rhinitis",
    bloodGroup: "A+",
    tags: ["Chronic", "Migraine", "Allergy", "Follow-up"],
    nextAppointment: { date: "22 May 2026, 10:30", reason: "Follow-up" },
    activePrescriptions: 2,
    openTasks: 1,
    consultations: [
      {
        id: "c1",
        date: "12 May 2026",
        time: "09:15",
        reason: "Headache and fatigue",
        clinician: "Dr. Emma Larsen",
        type: "In-person",
        status: "Completed",
      },
      {
        id: "c2",
        date: "8 Apr 2026",
        time: "11:00",
        reason: "Follow-up",
        clinician: "Dr. Emma Larsen",
        type: "In-person",
        status: "Completed",
      },
      {
        id: "c3",
        date: "3 Feb 2026",
        time: "14:20",
        reason: "Sore throat",
        clinician: "Dr. Emma Larsen",
        type: "Virtual",
        status: "Completed",
      },
      {
        id: "c4",
        date: "15 Jan 2026",
        time: "10:30",
        reason: "Annual check-up",
        clinician: "Dr. Emma Larsen",
        type: "In-person",
        status: "Completed",
      },
    ],
  },
  {
    id: "michael-chen",
    name: "Michael Chen",
    initials: "MC",
    avatarClassName: "bg-blue-100 text-blue-700",
    age: 45,
    gender: "Male",
    email: "michael.chen@example.com",
    phone: "+47 913 22 118",
    status: "Active",
    lastVisit: "12 May 2026",
    dateOfBirth: "3 Jun 1980",
    address: "Kirkeveien 42, 0368 Oslo, Norway",
    allergies: "None known",
    conditions: "Hypertension",
    bloodGroup: "O+",
    tags: ["Chronic", "Hypertension"],
    nextAppointment: { date: "19 May 2026, 09:00", reason: "Blood pressure check" },
    activePrescriptions: 1,
    openTasks: 0,
    consultations: [
      {
        id: "c1",
        date: "12 May 2026",
        time: "08:30",
        reason: "Blood pressure review",
        clinician: "Dr. Emma Larsen",
        type: "In-person",
        status: "Completed",
      },
      {
        id: "c2",
        date: "20 Mar 2026",
        time: "13:15",
        reason: "Routine check-up",
        clinician: "Dr. Emma Larsen",
        type: "In-person",
        status: "Completed",
      },
    ],
  },
  {
    id: "sarah-johnson",
    name: "Sarah Johnson",
    initials: "SJ",
    avatarClassName: "bg-rose-100 text-rose-700",
    age: 28,
    gender: "Female",
    email: "sarah.johnson@example.com",
    phone: "+47 914 55 902",
    status: "Active",
    lastVisit: "8 May 2026",
    dateOfBirth: "19 Sep 1997",
    address: "Bygdøy Allé 5, 0257 Oslo, Norway",
    allergies: "Shellfish",
    conditions: "Asthma",
    bloodGroup: "B+",
    tags: ["Asthma", "Follow-up"],
    nextAppointment: { date: "29 May 2026, 15:00", reason: "Asthma review" },
    activePrescriptions: 1,
    openTasks: 2,
    consultations: [
      {
        id: "c1",
        date: "8 May 2026",
        time: "11:45",
        reason: "Shortness of breath",
        clinician: "Dr. Emma Larsen",
        type: "Virtual",
        status: "Completed",
      },
    ],
  },
  {
    id: "james-wilson",
    name: "James Wilson",
    initials: "JW",
    avatarClassName: "bg-teal-100 text-teal-700",
    age: 62,
    gender: "Male",
    email: "james.wilson@example.com",
    phone: "+47 915 30 447",
    status: "Inactive",
    lastVisit: "3 May 2026",
    dateOfBirth: "2 Nov 1963",
    address: "Sognsveien 77, 0855 Oslo, Norway",
    allergies: "None known",
    conditions: "Type 2 diabetes",
    bloodGroup: "AB+",
    tags: ["Chronic", "Diabetes"],
    nextAppointment: { date: "Not scheduled", reason: "" },
    activePrescriptions: 3,
    openTasks: 0,
    consultations: [
      {
        id: "c1",
        date: "3 May 2026",
        time: "10:00",
        reason: "Diabetes review",
        clinician: "Dr. Emma Larsen",
        type: "In-person",
        status: "Completed",
      },
    ],
  },
  {
    id: "emily-davis",
    name: "Emily Davis",
    initials: "ED",
    avatarClassName: "bg-amber-100 text-amber-700",
    age: 31,
    gender: "Female",
    email: "emily.davis@example.com",
    phone: "+47 916 41 220",
    status: "Active",
    lastVisit: "2 May 2026",
    dateOfBirth: "27 Apr 1995",
    address: "Frognerveien 12, 0266 Oslo, Norway",
    allergies: "Latex",
    conditions: "None",
    bloodGroup: "A-",
    tags: ["New patient"],
    nextAppointment: { date: "16 May 2026, 09:30", reason: "Annual check-up" },
    activePrescriptions: 0,
    openTasks: 1,
    consultations: [
      {
        id: "c1",
        date: "2 May 2026",
        time: "09:00",
        reason: "New patient intake",
        clinician: "Dr. Emma Larsen",
        type: "In-person",
        status: "Completed",
      },
    ],
  },
  {
    id: "robert-martin",
    name: "Robert Martin",
    initials: "RM",
    avatarClassName: "bg-indigo-100 text-indigo-700",
    age: 50,
    gender: "Male",
    email: "robert.martin@example.com",
    phone: "+47 917 88 034",
    status: "Active",
    lastVisit: "1 May 2026",
    dateOfBirth: "14 Jul 1975",
    address: "Grünerløkka 3, 0554 Oslo, Norway",
    allergies: "None known",
    conditions: "High cholesterol",
    bloodGroup: "O-",
    tags: ["Chronic", "Follow-up"],
    nextAppointment: { date: "21 May 2026, 13:00", reason: "Lipid panel review" },
    activePrescriptions: 1,
    openTasks: 0,
    consultations: [
      {
        id: "c1",
        date: "1 May 2026",
        time: "14:30",
        reason: "Lipid panel review",
        clinician: "Dr. Emma Larsen",
        type: "In-person",
        status: "Completed",
      },
    ],
  },
  {
    id: "linda-smith",
    name: "Linda Smith",
    initials: "LS",
    avatarClassName: "bg-pink-100 text-pink-700",
    age: 47,
    gender: "Female",
    email: "linda.smith@example.com",
    phone: "+47 918 12 763",
    status: "Active",
    lastVisit: "30 Apr 2026",
    dateOfBirth: "8 Oct 1978",
    address: "Majorstuen 21, 0367 Oslo, Norway",
    allergies: "Pollen",
    conditions: "Allergic rhinitis",
    bloodGroup: "B-",
    tags: ["Allergy"],
    nextAppointment: { date: "14 May 2026, 11:00", reason: "Allergy follow-up" },
    activePrescriptions: 1,
    openTasks: 0,
    consultations: [
      {
        id: "c1",
        date: "30 Apr 2026",
        time: "10:15",
        reason: "Allergy symptoms",
        clinician: "Dr. Emma Larsen",
        type: "Virtual",
        status: "Completed",
      },
    ],
  },
];